version: '3.7'
services:
  r-container:
    depends_on:
      - sql-container  
    container_name: 'r-container'
    build: 
      context: './'
      dockerfile: './R/Dockerfile'
    ports:
      - '3838:3838'
   # command: ["/usr/src/wait-for-mssql.sh", "sql-container:1433", "R CMD BATCH /usr/src/build_tables.R"]
  sql-container:
    env_file:
      - './.env'
    container_name: 'sql-container'
    build: './SQL'
    ports:
      - '1433:1433'